### ISSUE TITLE
тип тваринки

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/pet-search#1]
https://github.com/DenisPitsul/pet-search/blob/26044fbdc0500765b17e314e41e4b94d2c1d046f/client/src/components/PetsList/index.jsx#L78
- не відображається назва, що за тваринка. Часто такі помилки пов'язані з запаковкою/розпаковкою даних в об'єкті

**Comment by DenisPitsul** [comment]
Fixed in commit:
https://github.com/DenisPitsul/pet-search/commit/d8f8d57d9c6022159088c0be203049d57533213e
