### ISSUE TITLE
контрольовані компоненти

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/pet-search#2]
https://github.com/DenisPitsul/pet-search/blob/26044fbdc0500765b17e314e41e4b94d2c1d046f/client/src/components/SideBar/index.jsx#L58
- консолька плюється помилками щодо того, що value та defaultValue не мають стояти разом, щось одне. Тут дані ті так надаються в value, тому `defaultValues` можна прибрати

**Comment by DenisPitsul** [comment]
Fixed in commit:
https://github.com/DenisPitsul/pet-search/commit/14363249345552bf8b0e80fc60863070d075e3d2
