### ISSUE TITLE
колір в випадаючому списку

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/pet-search#3]
https://github.com/DenisPitsul/pet-search/blob/26044fbdc0500765b17e314e41e4b94d2c1d046f/client/src/components/SideBar/PetsFilters.module.sass#L28
- зараз розкриті списки виглядають порожніми, оскільки мають білий текст на білому тлі. Можна задати колір options або ж селекту на active повісити

**Comment by DenisPitsul** [comment]
Fixed in commit:
https://github.com/DenisPitsul/pet-search/commit/cde852f47c230608b4ced398f48c32ec61a66b90
